name: Build Kwsify
on:
  - push
jobs:
  build:
    strategy:
      matrix:
        java:
          - 8
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build buildShadowJar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kwsify-executable
          path: build/libs/*-all.jar
          retention-days: 15
          compression-level: 9
