name: Build ROneBot
on:
  - push
jobs:
  build:
    strategy:
      matrix:
        java:
          - 11
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Publish to Gitlab
        run: ./gradlew publish
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}